
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <title>Terms and conditions</title>

    <meta property="og:image"
          content="https://apkabudget.in/storage/app/public/landing-page/meta/2024-01-12-65a156afdf80a.png"/>
    <meta property="og:title" content="Apka Budget"/>
    <meta property="og:description" content="LARGEST BOOKING SERVICE PLATFORM TRUSTED BY CUSTOMERS &amp; PROVIDERS">

    <link href="https://apkabudget.in/public/assets/provider-module/css/material-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://apkabudget.in/public/assets/landing/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://apkabudget.in/public/assets/landing/css/line-awesome.min.css"/>
    <link rel="stylesheet" href="https://apkabudget.in/public/assets/landing/css/owl.min.css"/>
    <link rel="stylesheet" href="https://apkabudget.in/public/assets/landing/css/main.css"/>

    <link rel="shortcut icon"
          href="https://apkabudget.in/storage/app/public/business/2024-01-05-65983aed60d54.png"
          type="image/x-icon"/>

    <style>
        :root {
            --body-bg: #f5fdff;
            --header-bg: #e8f2f2;
            --footer: #03000a;
            --footer-bottom: #e8f2f2;
        }

        .dark-theme {
            --body-bg: #121213;
            --header-bg: #11202be6;
            --footer: #001f35;
            --footer-bottom: #111a21;
        }
    </style>
</head>

<body>

<div id="landing-loader"></div>

    <div class="container pt-3">
        <section class="page-header bg__img" data-img="https://apkabudget.in/public/assets/landing/img/terms-page-header.png">
            <h3 class="title">Terms and conditions</h3>
        </section>
    </div>
    <section class="privacy-section py-5">
        <div class="container">
            <p><span style="background-color: rgb(45, 194, 107);"><strong><span style="color: rgb(236, 240, 241);">TERMS &amp; CONDITIONS</span></strong></span></p>
<hr>
<p>General Term &amp; Condition<br>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures to make the terms of this policy binding.</p>
<p>Please read the terms of use thoroughly and carefully</p>
<h3><span style="color: rgb(53, 152, 219);">Introduction</span></h3>
<p>(a)This Terms of use is made by the Apka Budget&nbsp; a company registered under the Indian Companies Act, 1956 and you as a User of the Apka Budget.</p>
<p>(b)This website www.apkabudget.in is completely owned operated by Apka Budget</p>
<p>(c) apkabudget.in or Apkabudget is one of India&rsquo;s biggest local and home base need service fulfillment platform with more than 10000 services,</p>
<h3><span style="color: rgb(53, 152, 219);">Definitions</span></h3>
<p>(a)"Use" or "Using" means to access, view, download, upload, or any other legal use or otherwise benefit from using the Apka Budget.</p>
<p>(b)"User&rdquo; or &ldquo;you" means any person who accesses or uses the Apka Budget for his own purpose or on behalf of someone else and includes any legal entity.</p>
<p>(c)&ldquo;User&rsquo;s Content&rdquo; means any content, including any text, data, information or other material, that you may upload, transmit or store using the functionality of the Apka Budget.</p>
<p>(d)&ldquo;Order&rdquo; or "Job": means any order placed for services through the Apka Budget Mobile Application/Website or any other medium or platform.</p>
<p>(e) &ldquo;Agreed Time&rdquo; means the appointed date and time for your services to be provided and as mentioned in the registration form.</p>
<p>(f)"Vendor" wherever applicable means a third party, which has agreed to co-operate with Apka Budget to offer its services.</p>
<p>(g)&ldquo;Apka Budget App&rdquo; means a Mobile Application owned and operated by Apka Budget and all screenshots, pages appearing, appended, available along with this Mobile Application.</p>
<p>(h)&ldquo;Apka Budget&rdquo; means collectively including all content provided through the Apka Budget app and website.</p>
<p>(i)&ldquo;Website&rdquo; means www.apkabudget.in and all web-pages appearing, appended, available along with this Website.</p>
<h2><span style="color: rgb(53, 152, 219);">Acceptance of Terms</span></h2>
<p>The terms and conditions set forth below ("Terms of Use") constitute a legally-binding agreement between Apka Budget and you. These Terms of Use contain provisions that define your limits, legal rights and obligations with respect to your use of and participation in &ldquo;Apka Budget&rdquo; website or mobile App. User is hereby accept all the term and condition are mentioned below</p>
<h2><span style="color: rgb(53, 152, 219);">Apkabudget Services Use</span></h2>
<p>User is hereby allowed to use the Apka Budget subject to acceptance of the terms and conditions of this Terms of Use and the Privacy Policy on the Apka Budget App and/or Website (&ldquo;Terms&rdquo;). User conveys acceptance to Terms every time the User uses the Apka Budget. User has discretion not to use the Apka Budget, so User&rsquo;s use of the Apka Budget, despite having the right and power of not to use, is construed as User has accepted the Terms.</p>
<p>Apka Budget can provide User, subject to acceptance of Terms, at its sole discretion, the User Name and Password (&ldquo;User Account&rdquo;). Apka Budget solely reserves the right to accept or reject application made by User for having User Account without obligation of explanation. Apka Budget&nbsp;reserves the right to store, evaluate, analyses, verify and authenticate the personal information and data provided by the User. The User hereby acknowledges that Apka Budget continues to maintain right to close the User Account without any prior notice for any reasons whatsoever it may be.</p>
<h2><span style="color: rgb(53, 152, 219);">Modification to Terms and Services</span></h2>
<p>Apka Budget retains the right to change the Terms from time to time and such modified Terms shall be immediately applicable. Every time You use the Apka Budget, shall constitute your acceptance of changes made to Terms Your use of the Website following any amendment of the Terms of Use will signify your assent to and acceptance of any revised Terms of Use. If you do not agree to abide by these or any future Terms of Use, please do not use or access the Website</p>
<h2><span style="color: rgb(53, 152, 219);">Eligibility and Accessibility</span></h2>
<p>Use of the Website is available only to individuals who are at least 18 years old and can form legally binding contracts under applicable law. You represent, acknowledge and agree that you are at least 18 years of age and to be legally capable of entering into a legal contract and has understood and voluntarily accepted the Terms.</p>
<p>You will be issued a user id and password to access your account. You must keep password confidential and not share it with any other person. You are responsible for all activity on your account, whether or not you authorized it. However, if you become aware of any unauthorized use of your account or your user id and password, please contact us immediately.</p>
<h2><span style="color: rgb(53, 152, 219);">Rules Of Conduct</span></h2>
<p>The ApkaBudget shall facilitate the User to order or book services online by using the ApkaBudget App and/or Website or calls. You acknowledge, agree that you have complete responsibility while ordering services through the ApkaBudget App and/or Website or calls. The User&rsquo;s discretion is required while using the ApkaBudget.</p>
<p>The ApkaBudget shall be used solely for User&rsquo;s non-exclusive, non-assignable, non-transferable and limited personal use and for no other purposes.</p>
<p>User&rsquo;s Use of the Apka Budget is subject to all applicable local, state, national laws and regulations wherever applicable. Except as specifically permitted in Terms, User shall have no right to copy, change, alter, amend, reverse engineer, decompile, reverse translate, disassemble, publish, disclose, display or make available, or in any other manner, decode the Apka Budget App and/or the Website.</p>
<h2><span style="color: rgb(53, 152, 219);">Ordering</span></h2>
<p>You agree that, any contract for the service ordered through use of Apka Budget App/ Website or calls is between &ldquo;You&rdquo; and &ldquo;Apka Budget&rdquo;, any contract for the supply of Apka Budget from the Apka Budget App and/or Website is between &ldquo;You&rdquo; and &ldquo;Apka Budget&rdquo;. You agree to take reasonable care when providing Apka Budget with your details and warrant that these details are accurate and complete at the time of ordering a service. Apka Budget and/or Services purchased/availed from theApka Budget App and/or Website is intended for your use only and that &ldquo;You&rdquo; are acting as an end customer only and not as an agent for another party while using the Apka Budget.</p>
<p>You understand that some type of services may be suitable for Users within certain age ranges and gender only unless mentioned otherwise. It is your sole responsibility to check whether the service you are ordering is suitable for the intended recipient.</p>
<p>You understand that, if the ordered service is within the capacity of the Apka Budget or it's associated vendors, Apka Budget will accept the contract and confirm it to you. If the details of the order are correct, the contract for the service will be confirmed by text message (SMS) and/or other medium to the User.</p>
<p>In case the service offered by Apka Budget is ordered, Apka Budget will confirm availability together with or separately from service.</p>
<p>The confirmation message will specify delivery details including the approximate service time specified by Apka Budget.</p>
<p>In case service is not possible for whatsoever reason, Apka Budget will let you know by text message (SMS), phone call and/or other medium. You understand and acknowledge that in unforeseeable events or Force Majeure events, Apka Budget may not be able to reach and/or communicate with you about the non-availability of the scheduled service.</p>
<h2><span style="color: rgb(53, 152, 219);">Prices And Payment</span></h2>
<p>All prices listed on the Apka Budget App and/or Website for services are correct at the time of publication and is as received vendors wherever applicable. While Apka Budget takes great care to keep them up to date</p>
<p>Visit Charge: Visit charge will be applicable on every order if customer denies to allow technician to complete the task after the visit. Its means once technician reached at customer place and client denied to accept solution then client have to pay minimum visiting charges which is mentioned in price list of every service category.</p>
<p>You will make payment in full to Service provider introduced to you through us for any services provided by such Service provider to you. You shall be required to pay the minimum charges or Repair charges along with the spare parts costs (whichever is high), if any installed or replaced / substituted in the products, to the Service Provider and the minimum service charges rates can be found on the Website of the Company. The Service charges shall be updated or amended from time to time and it shall be your responsibility to remain informed about the prevailing minimum charges for the services. And you should confirm the same from the Service provider about the service charge for the repair of the products before initiation of the Service. You agree that you will pay for all services you avail from the Service Provider either by way of cash, cheque, online payment, or any other payment method introduced by the company. Any payment made is non-refundable. After the completion of the Service, the final price charged to you by Apka Budget or the vendor may change at the time of delivery based on the latest menu and prices. Apka Budget&nbsp;reserves the right to alter the menu of the services available for usage on the Apka Budget App and/or Website and to delete and remove them if needed.</p>
<p>All prices listed on the Apka Budget App and/or Website for services by Apka Budget or its associated vendors listed on the Apka Budget App and/or Website reflect the price charged by Apka Budget or the vendor or its service partner at the time of listing. In the event where the vendor or the service partner informs Apka Budget immediately after placing the order by the User, about the change in price for the service, Apka Budget&nbsp;will try to make every possible effort to inform the User about the price difference and the User can choose to opt-out of the order at that time</p>
<p>The final cost towards the service will be confirmed after the inspection/ visit and before commencement of the service. Full payment must be made for all the particulars mentioned in the order. Payment has to be made in cash or, if available on the Apka Budget App and/or Website, by online payment including through credit card, debit card, net banking or wallet.</p>
<p>If you choose online payment, you must pay for your order before it is delivered. You shall ensure that online payment mode is secured, your debit/credit card details will be encrypted to prevent the possibility of someone being able to read them as they are sent over the internet. Your credit card company may also conduct necessary security checks to confirm about your identification before making any such payment.</p>
<h2><span style="color: rgb(53, 152, 219);">Service</span></h2>
<p>(a) The Company provides technology based services for providing home solutions in such as repairing / services of home products to you and you agree to obtain the services offered by third party technicians / Service Providers / Private Repair Professionals ("the Service Provider"). All the Services provided by the Company to you by means of your use of the registration on website of the Company are hereinafter referred to as the "Service."</p>
<p>(b) The entire Booking request as may be directed by the customer shall be forward to the concerned repair professional/service provider by the Company. The Service Provider shall be provided on availability basis and the same shall be communicated to the customer through the company internal mechanism procedure, however, it is clarified that on availability of the Service Provider, the communication details of Service Provider &amp; Customer shall be shared between both of them by the Company for the ease of both the parties to perform or exercise their rights &amp; obligations.</p>
<p>(c) In case, the Service Provider accepts the booking request made by you with the Company, your information is sent to the Service provider including your name, contact number etc. (d) Company shall endeavor reasonable efforts to bring you in contact with the Service Provider in order to render the required service subject to availability of the Service Provider in or around your location at the time of your booking request made to the Company.</p>
<p>(e) Service time quoted at the time of ordering is approximate only and may vary. Services will be delivered to the address as intimated by you while ordering. In case service is done by Company or vendor or a third party delivery service provider assigned by ApkaBudget, ApkaBudget will take reasonable care to deliver in a timely manner. No responsibility is taken for late service by ApkaBudget in either case.</p>
<p>(f) In case of a late service, no charges will either be voided or refunded by ApkaBudget.All risk in the service shall pass to you upon availing the service though ApkaBudget takes ample precaution to avoid any such risks.If you fail to accept the service at the time they are ready or ApkaBudget&nbsp;is unable to deliver at the nominated time due to your failure to provide appropriate instructions or authorizations, then the service shall be deemed to have been delivered to you and all risk and responsibility in relation to such orders shall pass to you. Any storage, insurance and other costs which ApkaBudget incurs as a result of the inability to service shall be your responsibility and you shall indemnify ApkaBudget&nbsp;in full for such cost.</p>
<p>(g) You will treat Service provider introduced to you through us with respect and not to cause damage to them or engage in any unlawful, threatening, harassing, abusive behavior or activity whilst using their service;</p>
<p>(h) Before handing over the products to be repaired the customer shall be cautious and ensure themselves about the credibility of the Service Provider and any defect in Service or theft/ damage to the asset; spare parts; accessories; products shall not be compensated by the Company in any manner whatsoever and it is clarified that that Company shall not be liable in any manner whatsoever, if any such harm/damage/ loss is caused to the Service Provider due to any such transfer or products to the Service provider for Service.You must ensure that at the time of service arrangements, including access where necessary, are in place for offering the service. ApkaBudget cannot be held liable for any damage, cost or expense incurred to such service as a result of a failure to provide adequate access or arrangements for service.</p>
<ol>
<li>To offer services at the place of service requested by you in your order;</li>
<li>To deliver within the time confirmed in your order;</li>
<li>To inform you if they expect that they are unable to meet the estimated service time.</li>
</ol>
<p>(I) ApkaBudget, the vendors or the service partners shall not be liable to you for any losses, liabilities, costs, damages, charges or expenses arising out of late delivery.</p>
<p>You understand and accept that it might not be possible for ApkaBudget, vendor or service partners to offer services to some locations. In such cases, ApkaBudget will inform you accordingly and arrange for cancellation of the order or service to any alternative delivery address.</p>
<h2><span style="color: rgb(53, 152, 219);">Information</span></h2>
<p>Where Apka Budget have requested information from you to provide service, you agree to provide Apka Budget with accurate and complete information.</p>
<p>You authorize Apka Budget to use, store or otherwise process your personal information in order to provide the service to you and for marketing and credit control purposes (the "Purpose"). The Purpose may include the disclosure of your personal information to selected third parties from time to time where Apka Budget believes that the services offered by such third parties may be of interest to you or where this is required by law or in order to provide the service to you in future You are entitled to request a copy of the said personal information Apka Budget holds about you. Please contact us if you wish to request copy of this information.</p>
<p class="MsoNormal" style="text-align: left;" align="center"><span style="color: rgb(53, 152, 219);"><strong><span lang="EN-IN" style="font-size: 22.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%;">Letter of Agreement</span></strong></span></p>
<p class="MsoNormal"><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">The Agreement is between<strong style="mso-bidi-font-weight: normal;"> AC</strong> <strong style="mso-bidi-font-weight: normal;">Partner</strong>&nbsp;<strong style="mso-bidi-font-weight: normal;">RBSR Apka Budget Home Service pvt Ltd. </strong>The Purpose of this Agreement is to define the scope of work and the schedule of payments agreed upon by Partner.</span></p>
<p class="MsoNormal"><strong style="mso-bidi-font-weight: normal;"><u><span lang="EN-IN" style="font-size: 16.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Terms &amp; Conditions:-</span></u></strong></p>
<p class="MsoListParagraphCxSpFirst" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 16.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Company Partner ko Per Month 30 leads Provide karegi.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 16.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Application ke through accepted leads ki puri zimmedari partner ki hogi.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 16.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Accepted leads on date &amp; time pr hi partner ko job deliver krna hoga.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 16.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Partner ki side se without reason cancellation lead ka pura amount partner company ko pay karega.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 16.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Company monthly aapko only 2 leads cancellation ka chance degi. 2 leads se Jayda cancellation hone par without refundable ID Close kardi jayegi.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 16.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Job complete hone par partner customer ko proper invoice or 2 month ka warranty dega.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 16.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Partner ki job recomplain aane par usko 3 days me hi resolve krna hoga otherwise Partner customer ko pura payment refund karega. Partner refund nhi krta hai to company partner ke against legally action legi &amp; partner ke Security amount se payment deduct karegi.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 16.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Partner ko job pr T-shirt &amp; Id card pehan kar jana mandatory hai.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 16.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Job done hone pr partner company ko same day commission pay karega. Otherwise new leads partner ko nhi di jayegi.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 16.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Call recording is mandatory (Agar customer booking cancel krta hai to aapke paas uska proof hoina chahiye)</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-align: justify; text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 16.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Registration recharge only 1 season k liye valid hoga.</span></p>
<p class="MsoListParagraphCxSpLast" style="text-align: justify; text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 16.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Registration amount season complete hone k bad hi refundable hoga. </span><span lang="EN-IN" style="font-size: 8.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">(All T&amp;C Apply).</span></p>
<p>Terms and Conditions: Fraud Prevention</p>
<p>1. Prohibition on Personal Sites: The company strictly prohibits the creation or management of personal sites using company resources or under the company's name.</p>
<p>2. Penalty for Non-Compliance: In the event of detection of fraudulent activities, including but not limited to creating or managing personal sites, the following penalties shall apply:</p>
<p>a. A one-time penalty of ₹10,000 (Indian Rupees Ten Thousand).</p>
<p>b. An additional payment of 50% (Fifty Percent) of the total value of the site(s) created or managed.</p>
<p>3. Legal Action: Failure to comply with the above penalties shall result in the company taking legal action against the individual, including but not limited to, civil and/or criminal proceedings.</p>
<p>Acknowledgement</p>
<p>By using company resources or services, you acknowledge that you have read, understood, and agreed to abide by these Terms and Conditions.</p>
<p>Note: These terms and conditions are subject to change without prior notice.</p>
<p>You can also consider adding:</p>
<p>- Definition of "personal site"<br>- Examples of prohibited activities<br>- Consequences of repeated offenses<br>- Dispute resolution mechanism<br>- Governing law and jurisdiction</p>
<p>Consult with a legal expert to ensure compliance with applicable laws and regulations.</p>
<p class="MsoNormal" style="text-align: left;" align="center"><span style="color: rgb(53, 152, 219);"><strong><span lang="EN-IN" style="font-size: 22.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%;">Letter of Agreement</span></strong></span></p>
<p class="MsoNormal"><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">The Agreement is between<strong style="mso-bidi-font-weight: normal;"> Painting</strong> <strong style="mso-bidi-font-weight: normal;">Partner </strong>&amp; <strong style="mso-bidi-font-weight: normal;">RBSR Apka Budget Home Service pvt Ltd. </strong>The Purpose of this Agreement is to define the scope of work and the schedule of payments agreed upon by Partner.</span></p>
<p class="MsoNormal"><span style="color: rgb(53, 152, 219);"><strong style="mso-bidi-font-weight: normal;"><u><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Terms &amp; Conditions:-</span></u></strong></span></p>
<p class="MsoListParagraphCxSpFirst" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Company partner ko per week 1-2 leads provide karegi.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Application ke through accepted leads ki puri zimmedari partner ki hogi.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Accepted leads on date &amp; time pr hi partner ko survey &amp; Job deliver krna hoga.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Company monthly aapko only 2 survey cancellation ka chance degi. 2 se Jayda cancellation hone par without refundable ID Close kardi jayegi.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Job complete hone par partner customer ko proper invoice or 1 year ka warranty dena hoga.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Partner ki job recomplain aane par usko 7 days me hi resolve krna hoga otherwise Partner customer ko pura payment refund karega. Partner refund nhi krta hai to company partner ke against legally action legi &amp; partner ke Security amount bhi nhi diya jayga.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Partner ko job pr T-shirt &amp; Id card pehan kar jana mandatory hai.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Job done hone pr partner company ko same day commission pay karega. Otherwise new leads partner ko nhi di jayegi.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Call recording is mandatory (Agar customer booking cancel krta hai to aapke paas uska proof hoina chahiye)</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-align: justify; text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Registration recharge only 6 month&nbsp; k liye valid hoga.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-align: justify; text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Customer &amp; Office Employee k sath koi bhi bad behaviour accepted nhi hoga. Agar aap esa krte hai toh company aapke sath continue nhi kregi or partner pe legally action legi.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-align: justify; text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Application par job completion ka update krna mandatory hai.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="text-align: justify; text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN-IN" style="font-size: 14.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN-IN" style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">Registration amount season complete hone k bad hi refundable hoga. </span><span lang="EN-IN" style="font-size: 7.0pt; mso-bidi-font-size: 8.0pt; line-height: 107%; font-family: 'Calibri Light',sans-serif; mso-ascii-theme-font: major-latin; mso-hansi-theme-font: major-latin; mso-bidi-theme-font: major-latin;">(All T&amp;C Apply).</span></p>
<h2><span style="color: rgb(53, 152, 219);">Personal Information And Privacy</span></h2>
<p>User understands and acknowledges that by choosing Apka Budget you have allowed Apka Budget to use your personal information.</p>
<p>User understands, acknowledges and agrees that although Apka Budget provides appropriate firewalls and protections, the Apka Budget is not hack proof. Data pilferage due to unauthorized hacking, virus attacks, technical issues is possible.</p>
<p>In case Apka Budget is required to disclose your personal information in order to assist the Government Authority or in adherence to the Court Order or to protect the interest of the Apka Budget Service and/or any particular user(s), Apka Budget will disclose it without obtaining prior permission from you. You authorize us to disclose your personal information.</p>
<h2><span style="color: rgb(53, 152, 219);">Ownership Of Intellectual Property</span></h2>
<p>All data, information is the property of Apka Budget or its Users. If you believe that the Apka Budget Service contains elements that infringe your intellectual property rights in your work, please notify Apka Budget immediately. If Apka Budget receives intellectual property right infringement claim notification and it is felt appropriate, Apka Budget may remove all such content from the Apka Budget App and/or Website which is indicated as infringing and/or take any other appropriate action.</p>
<h2><span style="color: rgb(53, 152, 219);">Disclaimer And Limitations Of Liability</span></h2>
<p>The Site is provided without any warranties or guarantees and in an "As Is" condition. You must bear the risks associated with the use of the Site.</p>
<p>(a). The information, recommendations provided to you on or through the Website is for general information purposes only and does not constitute any advice. The Company will reasonably keep the Website and its contents correct and up to date but does not guarantee that (the contents of) the Website are free of errors, defects, malware and viruses or that the Website are correct, up to date and accurate in all means.</p>
<p>(b). The Company shall further not be liable for damages resulting from the use of (or the inability to use) electronic means of communication with the Website, including &ndash; but not limited to &ndash; damages resulting from failure or delay in delivery of electronic communications, interception or manipulation of electronic communications by third parties or by computer programs used for electronic communications and transmission of viruses.</p>
<p>(C). Without prejudice to the generality of the section above, the total liability of Apka Budget to you for all liabilities arising out of this User Agreement is it in tort or contract is limited to the value of the product ordered by you.</p>
<p>(d). The quality of the services requested through the use of the Application or the Service is entirely the responsibility of the Service Provider who ultimately provides such services to you. The Company under no circumstance accepts liability in connection with and/or arising from the services provided by the Service Provider or any acts, action, behavior, conduct, and/or negligence on the part of the Service Provider. Any complaints about the services provided by the Service Provider should therefore be submitted to the Service Provider.</p>
<p>(e). The Apka Budget&nbsp; will be available for use, or that all services, features, functions, or operations will be available or be performed as described the services, The Apka Budget App and/or Website is not hack proof. The data may get pilfered, damaged, lost, garbled or become useless. Without limiting the foregoing, Apka Budget is not responsible or liable for any malicious code, delay, inaccurate, error or omissions arising out of your use of the Apka Budget.</p>
<p>(f). You understand, acknowledge and agree that you are assuming entire risk as to your data, quality, accuracy, performance, timeliness, adequacy, completeness, correctness, authenticity, safety, security, and validity of any and all features and functions of the Apka Budget service, including, without limitations, postings, and materials associated with your use of the Apka Budget service.</p>
<p>(g). You understand and agree that to the fullest extent permissible by law, the Apka Budget service, Apka Budget and their successors and assigns or any of their affiliates or their respective officers, directors, employees, agents, licensors, representatives, operational service providers, advertisers or suppliers shall not be liable for any loss or damage of any kind direct or indirect, in connection with or arising from use of the Apka Budget service or from this terms of use, including but not limited to, compensatory, consequential, incidental, indirect, special or punitive damages</p>
<h2><span style="color: rgb(53, 152, 219);">Indemnification</span></h2>
<p>You agree to indemnify and hold harmless Apka Budget and (as applicable) Apka Budget.in parent, subsidiaries, affiliates, third-parties and their respective shareholders, officers, directors, agents, and employees, from any losses, liabilities, damages, costs and expenses, claims or demand, or actions including reasonable attorneys' fees asserted against or incurred by apkabudget.in, made by any third party arising out of your breach or non-performance of terms of the User Agreement, Apka Budget Rules and Policies, or the documents they incorporate by reference, or your violation of any law, rules or regulations or the rights of a third party.</p>
<h2><span style="background-color: rgb(255, 255, 255); color: rgb(53, 152, 219);">Applicable Laws</span></h2>
<p>These Terms contains the entire understanding and agreement between User and Apka Budget and supersedes any and all prior or inconsistent understandings relating to Apka Budget Service and your use of Apka Budget Service. Terms cannot be changed or terminated orally. Any provision which must survive in order to allow us to enforce its meaning shall survive the termination of Terms. Terms and your use of Apka Budget&nbsp;Service is governed by, construed and enforced in accordance with the laws of India applicable to contracts made, executed and wholly performed on the Apka Budget Service, and, for the purposes of any and all legal or equitable actions, you specifically agree and submit to the exclusive jurisdiction and venue of the Courts of Noida, Ghaziabad, India and you will not object to such jurisdiction or venue on the grounds of lack of personal jurisdiction or otherwise.</p>
<h2><span style="color: rgb(53, 152, 219);">Force Majeure</span></h2>
<p>Without limiting the foregoing, under no circumstances shall Apka Budget be held liable for any damage or loss due to deficiency in performance of the Apka Budget Service resulting directly or indirectly from acts of nature, forces or causes beyond its reasonable control, including without limitation, Internet failures, computer equipment failures, telecommunication equipment failures, other equipment failures, electrical power failures.</p>
<h2><span style="color: rgb(53, 152, 219);">General Provisions</span></h2>
<p>Each provision of the Terms is independent of each other. If any provision of the Terms is found void and unenforceable, it will not affect the validity of the remaining provisions of Terms, which shall remain valid and enforceable.</p>
<h2><span style="color: rgb(53, 152, 219);">Complaints</span></h2>
<p>Apka Budget takes complaint very seriously and aim to respond to your complaint within 5 business days. All complaints to be addressed to&nbsp;<strong>Support@apkabudget.in</strong></p>
<p>If you do not accept and agree by this terms, You must not use Apka Budget</p>
<p>If you have any questions about the terms &amp; conditions, Please write us at: support@apkabudget.in</p>
<p><strong><span style="color: rgb(45, 194, 107);">&nbsp;</span><span style="color: rgb(45, 194, 107);">or call us on</span><span style="color: rgb(45, 194, 107);"> </span><span style="color: rgb(224, 62, 45);">96-25-97-96-96</span></strong></p>
<p>This document was last updated on march1, 2024</p>
        </div>
    </section>

<footer>
    <div class="footer-top">
        <div class="container">
            <div class="footer__wrapper">
                <div class="footer__wrapper-widget">
                    <div class="cont">
                        <a href="#" class="logo">
                            <img src="https://apkabudget.in/storage/app/public/business/2024-02-08-65c48202b9101.png" alt="Logo">
                        </a>
                        <div class="app-btns">
                                                            <a href="https://apkabudget.com/" class="d-block">
                                    <img class="w-100" src="https://apkabudget.in/public/assets/landing/img/app-btn/app-store.png" alt="App store">
                                </a>
                            
                                                            <a href="https://play.google.com/store/apps/details?id=com.apkabudget.customer" class="d-block">
                                    <img class="w-100" src="https://apkabudget.in/public/assets/landing/img/app-btn/google-play.png" alt="Play store">
                                </a>
                                                    </div>
                    </div>
                </div>
                <div class="footer__wrapper-widget">
                    <ul class="footer__wrapper-link">
                        <li>
                            <a href="https://apkabudget.in">Home</a>
                        </li>
                        <li>
                            <a href="https://apkabudget.in/page/about-us">About us</a>
                        </li>
                        <li>
                            <a href="https://apkabudget.in/page/contact-us">Contact us</a>
                        </li>
                        <li>
                            <a href="https://apkabudget.in/page/privacy-policy">Privacy policy</a>
                        </li>
                                                    <li>
                                <a href="https://apkabudget.in/page/terms-and-conditions">Terms &amp; conditions</a>
                            </li>
                                                                                                    <li>
                                <a href="https://apkabudget.in/page/refund-policy">Refund policy</a>
                            </li>
                                            </ul>
                </div>
                <div class="footer__wrapper-widget">
                    <div class="footer__wrapper-contact">
                        <img class="icon" src="https://apkabudget.in/public/assets/landing/img/footer/mail.png" alt="Footer">
                        <h6>
                            Send us mail
                        </h6>
                        <a href="Mailto:support@apkabudget.in">support@apkabudget.in</a>
                    </div>
                </div>
                <div class="footer__wrapper-widget">
                    <div class="footer__wrapper-contact">
                        <img class="icon" src="https://apkabudget.in/public/assets/landing/img/footer/tel.png" alt="Footer">
                        <h6>
                            Contact us
                        </h6>
                        <a href="Tel:+919625979696">+919625979696</a>
                    </div>
                </div>
                <div class="footer__wrapper-widget">
                    <div class="footer__wrapper-contact">
                        <img class="icon" src="https://apkabudget.in/public/assets/landing/img/cta-icon.png" alt="Footer">
                        <h6>
                            Become a provider
                        </h6>
                                                    <div>
                                <a href="https://apkabudget.in/provider/auth/sign-up"
                                   class="cmn--btn">Register here</a>
                            </div>
                                            </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom text-center py-3">
        All rights reserved By @ RBSR Apka Budget Home Services PVT. LTD.
    </div>
</footer>

<script src="https://apkabudget.in/public/assets/landing/js/jquery-3.6.0.min.js"></script>
<script src="https://apkabudget.in/public/assets/landing/js/viewport.jquery.js"></script>
<script src="https://apkabudget.in/public/assets/landing/js/wow.min.js"></script>
<script src="https://apkabudget.in/public/assets/landing/js/owl.min.js"></script>
<script src="https://apkabudget.in/public/assets/landing/js/bootstrap.min.js"></script>
<script src="https://apkabudget.in/public/assets/landing/js/custom.js"></script>

<script>
    "use strict";

    (function ($) {
        $(document).ready(function () {
            $(".accordion-title").on("click", function (e) {
                var element = $(this).parent(".accordion-item");
                if (element.hasClass("open")) {
                    element.removeClass("open");
                    element.find(".accordion-content").removeClass("open");
                    element.find(".accordion-content").slideUp(200, "swing");
                } else {
                    element.addClass("open");
                    element.children(".accordion-content").slideDown(200, "swing");
                    element
                        .siblings(".accordion-item")
                        .children(".accordion-content")
                        .slideUp(200, "swing");
                    element.siblings(".accordion-item").removeClass("open");
                    element
                        .siblings(".accordion-item")
                        .find(".accordion-title")
                        .removeClass("open");
                    element
                        .siblings(".accordion-item")
                        .find(".accordion-content")
                        .slideUp(200, "swing");
                }
            });

            let fixed_top = $(".navbar-bottom");
            $(window).on("scroll", function () {
                if ($(this).scrollTop() > 110) {
                    fixed_top.addClass("active");
                } else {
                    fixed_top.removeClass("active");
                }
            });

            $(".owl-prev").html('<i class="fas fa-angle-left">');
            $(".owl-next").html('<i class="fas fa-angle-right">');

            if ($(".wow").length) {
                var wow = new WOW({
                    boxClass: "wow",
                    animateClass: "animated",
                    offset: 0,
                    mobile: true,
                    live: true,
                });
                wow.init();
            }

            $(".mode--toggle").on("click", function () {
                setTheme(localStorage.getItem("theme"));
            });
            if (localStorage.getItem("theme") == "light-theme") {
                localStorage.setItem("theme", "dark-theme");
            } else {
                localStorage.setItem("theme", "light-theme");
            }
            setTheme(localStorage.getItem("theme"));

            function setTheme(theme) {
                if (theme == "dark-theme") {
                    localStorage.setItem("theme", "light-theme");
                    $("html").addClass(theme);
                    $(".mode--toggle").find("img").attr("src", "https://apkabudget.in/public/assets/landing/img/moon.png");
                } else {
                    localStorage.setItem("theme", "dark-theme");
                    $("html").removeClass("dark-theme");
                    $(".mode--toggle").find("img").attr("src", "https://apkabudget.in/public/assets/landing/img/sun.png");
                }
            }

            $(".nav-toggle").on("click", () => {
                $(".nav-toggle").toggleClass("active");
                $(".menu").toggleClass("active");
                $(".navbar-bottom-wrapper").toggleClass("rounded-0");
            });

            let siteDirection = "ltr";
            siteDirection = siteDirection === 'rtl';

            let testimonial = $(".testimonial-slider")
                .on("initialized.owl.carousel changed.owl.carousel", function (e) {
                    if (!e.namespace) {
                        return;
                    }
                    var carousel = e.relatedTarget;
                    $(".slider-counter").text(
                        carousel.relative(carousel.current()) +
                        1 +
                        " / " +
                        carousel.items().length
                    );
                })
                .owlCarousel({
                    items: 1,
                    loop: true,
                    margin: 0,
                    nav: false,
                    mouseDrag: true,
                    touchDrag: true,
                    center: true,
                    autoplay: true,
                    rtl: siteDirection,
                    speed: 1000,
                    navSpeed: 1000,
                    autoplaySpeed: 1000,
                    smartSpeed: 1000,
                    fluidSpeed: 1000,
                    responsive: {
                        768: {
                            items: 3,
                        },
                    },
                });
            $(".testimonial-owl-prev").on("click", function () {
                testimonial.trigger("prev.owl.carousel");
            });
            $(".testimonial-owl-next").on("click", function () {
                testimonial.trigger("next.owl.carousel");
            });

            var app = $(".app-slider")
                .on("initialized.owl.carousel changed.owl.carousel", function (e) {
                    if (!e.namespace) {
                        return;
                    }
                    var carousel = e.relatedTarget;
                    $(".app-counter").text(
                        carousel.relative(carousel.current()) +
                        1 +
                        " / " +
                        carousel.items().length
                    );
                })
                .owlCarousel({
                    items: 1,
                    loop: true,
                    margin: 0,
                    nav: false,
                    mouseDrag: false,
                    touchDrag: false,
                    autoplay: true,
                    autoplayTimeout: 2500,
                    rtl: siteDirection,
                    speed: 1000,
                    autoplaySpeed: 1000,
                    smartSpeed: 1000,
                    fluidSpeed: 1000,
                });
            $(".app-owl-prev").on("click", function () {
                app.trigger("prev.owl.carousel");
                $(".owl-stage").css("transition", "all 0.3s ease 1s !important");
            });
            $(".app-owl-next").on("click", function () {
                app.trigger("next.owl.carousel");
            });

            let owl = $(".service-slider").owlCarousel({
                margin: 0,
                responsiveClass: true,
                nav: false,
                dots: false,
                loop: false,
                rtl: siteDirection,
                autoplay: true,
                autoplayTimeout: 1500,
                autoplayHoverPause: true,
                mouseDrag: true,
                touchDrag: true,
                responsive: {
                    0: {
                        items: 1,
                    },
                    500: {
                        items: 2,
                    },
                    768: {
                        items: 3,
                    },
                    992: {
                        items: 3,
                    },
                    1200: {
                        items: 4,
                    },
                },
            });
            /*Slider Trigger*/
            $(".service-slide-prev").on("click", function () {
                owl.trigger("prev.owl.carousel");
            });
            $(".service-slide-next").on("click", function () {
                owl.trigger("next.owl.carousel");
            });

            $(".service-inner-slider").owlCarousel({
                loop: false,
                margin: 0,
                responsiveClass: true,
                nav: false,
                dots: false,
                autoplay: true,
                rtl: siteDirection,
                autoplayTimeout: 1500,
                autoplayHoverPause: true,
                responsive: {
                    0: {
                        items: 3,
                        margin: 10,
                    },
                    500: {
                        items: 4,
                        margin: 10,
                    },
                    576: {
                        items: 3,
                        margin: 10,
                    },
                    768: {
                        items: 5,
                        margin: 20,
                    },
                    992: {
                        items: 6,
                        margin: 30,
                    },
                    1200: {
                        items: 6,
                        margin: 40,
                    },
                },
            });
            $("[data-target]").on("click", function () {
                const slide = $(this).data("target");
                $(".service__item-popup").each(function () {
                    if ($(this).data("slide") === slide) {
                        $(this).addClass("active");
                    } else {
                        $(this).removeClass("active");
                    }
                });
            });
            $(".close__popup").on("click", function () {
                $(".service__item-popup").removeClass("active");
            });
        });
    })(jQuery);
</script>


</body>
</html>
